=== homeappstudy/UCL-Health-On-The-Move-aRMT-protocols/docs/protocol-schema-0.0.5.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "id": "http://radar-base.org/armt/protocol/schema#",
  "$id": "http://radar-base.org/armt/protocol/schema#",
  "type": "object",
  "title": "RADAR-base protocol for the aRMT app questionnaire delivery",
  "description": "A protocol for the RADAR-base aRMT app describes what questionnaires should be proposed to participants at what time. It controls notification times, label text and the questionnaire sources. The reference questionnaire app is described on the wiki page https://radar-base.atlassian.net/wiki/spaces/RAD/pages/463241217/Protocol+Schedule.",
  "version": "0.0.5",
  "required": [
    "version",
    "schemaVersion",
    "name",
    "protocols"
  ],
  "properties": {
    "version": {
      "$id": "#/properties/version",
      "type": "string",
      "title": "Protocol version",
      "description": "Update this version whenever the aRMT app should read any changes. Use semantic versioning for the version.",
      "examples": [
        "0.2.3"
      ],
      "pattern": "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)(-(0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*)(\\.(0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\\+[0-9a-zA-Z-]+(\\.[0-9a-zA-Z-]+)*)?$"
    },
    "schemaVersion": {
      "$id": "#/properties/schemaVersion",
      "type": "string",
      "title": "The version of this schema",
      "description": "The version of this schema describing the protocol structure. Use semantic versioning for the version.",
      "default": "",
      "examples": [
        "0.0.2"
      ],
      "pattern": "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)(-(0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*)(\\.(0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\\+[0-9a-zA-Z-]+(\\.[0-9a-zA-Z-]+)*)?$"
    },
    "name": {
      "$id": "#/properties/name",
      "type": "string",
      "title": "Protocol set name",
      "description": "The name of the set of protocols. It should match the study that the protocol is being used in.",
      "examples": [
        "RADAR MDD KCL s1"
      ]
    },
    "healthIssues": {
      "$id": "#/properties/healthIssues",
      "type": "array",
      "title": "Health issues",
      "description": "Study area of health issues that are covered by the questionnaire.",
      "items": {
        "$id": "#/properties/healthIssues/items",
        "type": "string",
        "title": "Health issue",
        "default": "",
        "examples": [
          "depression"
        ]
      }
    },
    "protocols": {
      "$id": "#/properties/protocols",
      "type": "array",
      "title": "Questionnaire protocols",
      "description": "List of questionnaire protocols in the study protocol.",
      "items": {
        "$id": "#/properties/protocols/items",
        "type": "object",
        "title": "Questionnaire protocol",
        "description": "Single questionnaire protocol.",
        "required": [
          "name",
          "showIntroduction",
          "questionnaire",
          "startText",
          "endText",
          "warn",
          "estimatedCompletionTime",
          "protocol"
        ],
        "properties": {
          "name": {
            "$id": "#/properties/protocols/items/properties/name",
            "type": "string",
            "title": "Protocol name",
            "examples": [
              "PHQ8"
            ]
          },
          "showIntroduction": {
            "$id": "#/properties/protocols/items/properties/showIntroduction",
            "type": "boolean",
            "title": "Show an introduction",
            "description": "True if an introduction to the questionnaire should be shown, false otherwise. The contents of the introduction are defined by the 'startText' property.",
            "default": "",
            "examples": [
              false
            ]
          },
          "showInCalendar": {
            "$id": "#/properties/protocols/items/properties/showInCalendar",
            "type": "boolean",
            "title": "Whether the questionnaire should show up on the task calendar.",
            "description": "True if the questionnaire should show up on the task calendar and show task information, or false, if it should be hidden (for example, for randomised questionnaires).",
            "default": true,
            "examples": [
              false
            ]
          },          
          "isDemo": {
            "$id": "#/properties/protocols/items/properties/isDemo",
            "type": "boolean",
            "title": "Whether the questionnaire is only a demo",
            "description": "True if the questionnaire is only a demo, so the data for the questionnaire should not be sent to the server.",
            "default": false,
            "examples": [
              true
            ]
          },
          "order": {
            "$id": "#/properties/protocols/items/properties/order",
            "type": "integer",
            "title": "Order for showing tasks in the home page",
            "description": "Order for choosing tasks to prioritize in the home page when multiple tasks are pending and order for showing clinical tasks, where 0 has the highest order/priority.",
            "default": 0,
            "examples": [
              0
            ]
          },
          "questionnaire": {
            "$id": "#/properties/protocols/items/properties/questionnaire",
            "type": "object",
            "title": "Questionnaire to use",
            "description": "Reference to the questionnaire specification. This defines the questions, field type, branching logic etc.",
            "required": [
              "repository",
              "name",
              "avsc"
            ],
            "properties": {
              "repository": {
                "$id": "#/properties/protocols/items/properties/questionnaire/properties/repository",
                "type": "string",
                "title": "Repository URL",
                "default": "",
                "examples": [
                  "https://raw.githubusercontent.com/RADAR-base/RADAR-REDCap-aRMT-Definitions/master/questionnaires/"
                ]
              },
              "name": {
                "$id": "#/properties/protocols/items/properties/questionnaire/properties/name",
                "type": "string",
                "title": "Questionnaire name",
                "description": "Name should match file name under the URL provided in the repository property.",
                "default": "",
                "examples": [
                  "phq8"
                ]
              },
              "avsc": {
                "$id": "#/properties/protocols/items/properties/questionnaire/properties/avsc",
                "type": "string",
                "title": "Schema",
                "description": "Avro Schema name as defined in RADAR-Schemas.",
                "examples": [
                  "notification"
                ]
              }
            }
          },
          "startText": {
            "$id": "#/properties/protocols/items/properties/startText",
            "type": "object",
            "title": "Start text",
            "description": "Text shown in the app before starting a questionnaire. Enable it with the 'showIntroduction' property.",
            "required": ["en"],
            "patternProperties": {
              "^[a-z][a-z](-[a-zA-Z0-9]+)*$": {"type": "string", "description": "Text in the language corresponding to property name. The property name should be a ISO 639-1 two letter language code or BCP-47 language tag.", "examples": ["en", "nl", "en-US"]}
            },
            "additionalProperties": false
          },
          "endText": {
            "$id": "#/properties/protocols/items/properties/endText",
            "type": "object",
            "title": "End text",
            "description": "Text shown in the app after finishing a questionnaire.",
            "required": ["en"],
            "patternProperties": {
              "^[a-z][a-z](-[a-zA-Z0-9]+)*$": {"type": "string", "description": "Text in the language corresponding to property name. The property name should be a ISO 639-1 two letter language code or BCP-47 language tag.", "examples": ["en", "nl", "en-US"]}
            },
            "additionalProperties": false
          },
          "warn": {
            "$id": "#/properties/protocols/items/properties/warn",
            "type": "object",
            "title": "Warning text",
            "description": "Warning shown when the questionnaire has not been filled.",
            "required": ["en"],
            "patternProperties": {
              "^[a-z][a-z](-[a-zA-Z0-9]+)*$": {"type": "string", "description": "Text in the language corresponding to property name. The property name should be a ISO 639-1 two letter language code or BCP-47 language tag.", "examples": ["en", "nl", "en-US"]}
            },
            "additionalProperties": false
          },
          "estimatedCompletionTime": {
            "$id": "#/properties/protocols/items/properties/estimatedCompletionTime",
            "type": "integer",
            "title": "Estimated completion time",
            "description": "Estimated completion time in minutes.",
            "examples": [
              1
            ]
          },
          
          "protocol": {
            "$id": "#/properties/protocols/items/properties/protocol",
            "type": "object",
            "title": "Questionnaire protocol",
            "description": "Protocol including schedule for the questionnaire.",
            "required": [
              "repeatProtocol",
              "repeatQuestionnaire",
              "reminders"
            ],
            "properties": {
              "repeatProtocol": {
                "$id": "#/properties/protocols/items/properties/protocol/properties/repeatProtocol",
                "type": "object",
                "title": "Protocol repetition",
                "description": "How frequently the protocol should be repeated for each participant.",
                "required": [
                  "unit",
                  "amount"
                ],
                "default": {
                  "unit": "day",
                  "amount": 7
                },
                "properties": {
                  "unit": {
                    "$id": "#/properties/protocols/items/properties/protocol/properties/repeatProtocol/properties/unit",
                    "type": "string",
                    "enum": ["min", "hour", "day", "week", "month", "year"],
                    "title": "Amount unit",
                    "description": "Duration unit attached to the amount property in repeatProtocol.",
                    "examples": [
                      "day"
                    ]
                  },
                  "amount": {
                    "$id": "#/properties/protocols/items/properties/protocol/properties/repeatProtocol/properties/amount",
                    "type": "integer",
                    "title": "Amount of time",
                    "description": "Modified by the unit property in repeatProtocol.",
                    "examples": [
                      7
                    ]
                  }
                },
                "additionalProperties": false
              },
              "repeatQuestionnaire": {
                "$id": "#/properties/protocols/items/properties/protocol/properties/repeatQuestionnaire",
                "type": "object",
                "title": "Questionnaire repetitions",
                "description": "What time of day questionnaires should be posed. The day that questionnaires are posed are specified with repeatProtocol, the local time is defined by this repeatQuestionnaire (units offset from repeat from midnight repeatProtocol day).",
                "required": [
                  "unit",
                  "unitsFromZero"
                ],
                "properties": {
                  "unit": {
                    "$id": "#/properties/protocols/items/properties/protocol/properties/repeatQuestionnaire/properties/unit",
                    "type": "string",
                    "enum": ["min", "hour", "day"],
                    "title": "Amount unit",
                    "description": "Duration unit attached to the unitsFromZero property in repeatQuestionnaire.",
                    "examples": [
                      "min"
                    ]
                  },
                  "unitsFromZero": {
                    "$id": "#/properties/protocols/items/properties/protocol/properties/repeatQuestionnaire/properties/unitsFromZero",
                    "type": "array",
                    "title": "Times starting at midnight",
                    "description": "Times, starting from midnight, that a protocol should be suggested. The date of the midnight in question is determined by repeatProtocol.",
                    "items": {
                      "$id": "#/properties/protocols/items/properties/protocol/properties/repeatQuestionnaire/properties/unitsFromZero/items",
                      "type": "integer",
                      "title": "Amount of time",
                      "description": "Modified by the unit property in repeatQuestionnaire",
                      "examples": [
                        600
                      ]
                    }
                  }
                }
              },
              "clinicalProtocol": {
                "$id": "#/properties/protocols/items/properties/protocol/properties/clinicalProtocol",
                "type": "object",
                "title": "Clinical protocol",
                "description": "Defines repetitions of the protocol after a clinical visit.",
                "required": [
                  "repeatAfterClinicVisit"
                ],
                "properties": {
                  "requiresInClinicCompletion": {
                    "$id": "#/properties/protocols/items/properties/protocol/properties/repeatQuestionnaire",
                    "type": "boolean",
                    "title": "Requires in-clinic completion.",
                    "description": "Whether the test should be performed during a clinical visit.",
                    "examples": [
                      true
                    ]
                  },
                  "repeatAfterClinicVisit": {
                    "$id": "#/properties/protocols/items/properties/protocol/properties/repeatQuestionnaire",
                    "type": "object",
                    "title": "Test repetitions",
                    "description": "When to repeat the test.",
                    "required": [
                      "unit",
                      "unitsFromZero"
                    ],
                    "properties": {
                      "unit": {
                        "$id": "#/properties/protocols/items/properties/protocol/properties/repeatQuestionnaire/properties/unit",
                        "type": "string",
                        "enum": ["min", "hour", "day"],
                        "title": "Amount unit",
                        "description": "Duration unit attached to the unitsFromZero property in repeatAfterClinicVisit.",
                        "examples": [
                          "min"
                        ]
                      },
                      "unitsFromZero": {
                        "$id": "#/properties/protocols/items/properties/protocol/properties/repeatQuestionnaire/properties/unitsFromZero",
                        "type": "array",
                        "title": "Times",
                        "description": "Times, starting from clinic visit, that a protocol should start.",
                        "items": {
                          "$id": "#/properties/protocols/items/properties/protocol/properties/repeatQuestionnaire/properties/unitsFromZero/items",
                          "type": "integer",
                          "title": "Amount of time",
                          "description": "Modified by the unit property in repeatAfterClinicVisit",
                          "examples": [
                            600
                          ]
                        }
                      }
                    }
                  }
                },
                "additionalProperties": false
              },
              "reminders": {
                "$id": "#/properties/protocols/items/properties/protocol/properties/reminders",
                "type": "object",
                "title": "Reminder schedule",
                "description": "When and how often to remind participants that a questionnairie still has to be filled out.",
                "required": [
                  "unit",
                  "amount",
                  "repeat"
                ],
                "properties": {
                  "unit": {
                    "$id": "#/properties/protocols/items/properties/protocol/properties/reminders/properties/unit",
                    "type": "string",
                    "enum": ["min", "hour", "day", "week", "month", "year"],
                    "title": "Amount unit",
                    "description": "Duration unit modifing the amount property in reminders.",
                    "examples": [
                      "day"
                    ]
                  },
                  "amount": {
                    "$id": "#/properties/protocols/items/properties/protocol/properties/reminders/properties/amount",
                    "type": "integer",
                    "title": "Amount of time",
                    "description": "Time to wait after the previous notification. Modified by the unit property in reminders.",
                    "examples": [
                      0
                    ]
                  },
                  "repeat": {
                    "$id": "#/properties/protocols/items/properties/protocol/properties/reminders/properties/repeat",
                    "type": "integer",
                    "title": "Repetitions",
                    "description": "Number of reminders to send.",
                    "default": 0,
                    "examples": [
                      0
                    ]
                  }
                },
                "additionalProperties": false
              }
            }
          }
        }
      }
    }
  },
  "additionalProperties": false
}

=== homeappstudy/UCL-Health-On-The-Move-aRMT-protocols/RADAR-MDD-KCL-s1/protocol.json
{
  "version": "0.2.5",
  "schemaVersion": "0.0.2",
  "name": "RADAR MDD KCL s1",
  "healthIssues": ["depression"],
  "protocols": [
    {
      "name": "THINC-IT",
      "showIntroduction": false,
      "questionnaire": {
        "repository": "https://raw.githubusercontent.com/RADAR-base/RADAR-REDCap-aRMT-Definitions/master/questionnaires/",
        "name": "thinc_it",
        "avsc": "notification"
      },
      "startText": {
        "en": "",
        "it": "",
        "nl": "",
        "da": "",
        "de": "",
        "es": ""
      },
      "endText": {
        "en": "",
        "it": "",
        "nl": "",
        "da": "",
        "de": "",
        "es": ""
      },
      "warn": {
        "en": "Requires a quiet space.",
        "it": "Richiede uno spazio tranquillo.",
        "nl": "Vereist een rustige ruimte.",
        "da": "Kræver et stille rum.",
        "de": "Benötigt einen ruhigen Platz.",
        "es": "Requiere un espacio tranquilo."
      },
      "estimatedCompletionTime": 1,
      "protocol": {
        "repeatProtocol": {
          "unit": "day",
          "amount": 42
        },
        "repeatQuestionnaire": {
          "unit": "min",
          "unitsFromZero": [660]
        },
        "reminders": {
          "unit": "day",
          "amount": 0,
          "repeat": 0
        }
      }
    },
    {
      "name": "PHQ8",
      "showIntroduction": false,
      "questionnaire": {
        "repository": "https://raw.githubusercontent.com/RADAR-base/RADAR-REDCap-aRMT-Definitions/master/questionnaires/",
        "name": "phq8",
        "avsc": "questionnaire"
      },
      "startText": {
        "en": "This questionnaire is known as the PHQ8. Clinicians use it to assess current depression in patients. Please note that none of your answers will be collected today. Thank you for taking part in this focus group.",
        "it": "",
        "nl": "",
        "da": "",
        "de": "",
        "es": ""
      },
      "endText": {
        "en": "Thank you for taking the time today.",
        "it": "",
        "nl": "",
        "da": "",
        "de": "",
        "es": ""
      },
      "warn": {
        "en": "",
        "it": "",
        "nl": "",
        "da": "",
        "de": "",
        "es": ""
      },
      "estimatedCompletionTime": 3,
      "protocol": {
        "repeatProtocol": {
          "unit": "day",
          "amount": 14
        },
        "repeatQuestionnaire": {
          "unit": "min",
          "unitsFromZero": [570]
        },
        "reminders": {
          "unit": "day",
          "amount": 0,
          "repeat": 0
        },
        "completionWindow": {
          "unit": "day",
          "amount": 3
        }
      }
    },
    {
      "name": "RSES",
      "showIntroduction": false,
      "questionnaire": {
        "repository": "https://raw.githubusercontent.com/RADAR-base/RADAR-REDCap-aRMT-Definitions/master/questionnaires/",
        "name": "rses",
        "avsc": "questionnaire"
      },
      "startText": {
        "en": "",
        "it": "",
        "nl": "",
        "da": "",
        "de": "",
        "es": ""
      },
      "endText": {
        "en": "",
        "it": "",
        "nl": "",
        "da": "",
        "de": "",
        "es": ""
      },
      "warn": {
        "en": "",
        "it": "",
        "nl": "",
        "da": "",
        "de": "",
        "es": ""
      },
      "estimatedCompletionTime": 3,
      "protocol": {
        "repeatProtocol": {
          "unit": "day",
          "amount": 14
        },
        "repeatQuestionnaire": {
          "unit": "min",
          "unitsFromZero": [600]
        },
        "reminders": {
          "unit": "day",
          "amount": 0,
          "repeat": 0
        },
        "completionWindow": {
          "unit": "day",
          "amount": 3
        }
      }
    },
    {
      "name": "DEMO",
      "showIntroduction": true,
      "questionnaire": {
        "repository": "https://raw.githubusercontent.com/RADAR-base/RADAR-REDCap-aRMT-Definitions/master/questionnaires/",
        "name": "esm-demo",
        "avsc": "questionnaire"
      },
      "startText": {
        "en": "",
        "it": "",
        "nl": "",
        "da": "",
        "de": "",
        "es": ""
      },
      "endText": {
        "en": "",
        "it": "",
        "nl": "",
        "da": "",
        "de": "",
        "es": ""
      },
      "warn": {
        "en": "",
        "it": "",
        "nl": "",
        "da": "",
        "de": "",
        "es": ""
      },
      "estimatedCompletionTime": 3,
      "protocol": {
        "repeatProtocol": {
          "unit": "year",
          "amount": 9999
        },
        "repeatQuestionnaire": {
          "unit": "min",
          "unitsFromZero": [540]
        },
        "reminders": {
          "unit": "day",
          "amount": 0,
          "repeat": 0
        }
      }
    },
    {
      "name": "AUDIO",
      "showIntroduction": false,
      "questionnaire": {
        "repository": "https://raw.githubusercontent.com/RADAR-base/RADAR-REDCap-aRMT-Definitions/master/questionnaires/",
        "name": "audio",
        "avsc": "questionnaire"
      },
      "startText": {
        "en": "",
        "it": "",
        "nl": "",
        "da": "",
        "de": "",
        "es": ""
      },
      "endText": {
        "en": "",
        "it": "",
        "nl": "",
        "da": "",
        "de": "",
        "es": ""
      },
      "warn": {
        "en": "Find a quiet space.",
        "it": "Trova uno spazio tranquillo.",
        "nl": "Zoek een stille ruimte.",
        "da": "Find et roligt sted.",
        "de": "Suchen Sie sich einen ruhigen Platz.",
        "es": "Encuentra un espacio tranquilo."
      },
      "estimatedCompletionTime": 3,
      "protocol": {
        "repeatProtocol": {
          "unit": "day",
          "amount": 42
        },
        "repeatQuestionnaire": {
          "unit": "min",
          "unitsFromZero": [690]
        },
        "reminders": {
          "unit": "day",
          "amount": 0,
          "repeat": 0
        },
        "completionWindow": {
          "unit": "day",
          "amount": 3
        }
      }
    },
    {
      "name": "AUDIO_2",
      "showIntroduction": false,
      "questionnaire": {
        "repository": "https://raw.githubusercontent.com/RADAR-base/RADAR-REDCap-aRMT-Definitions/master/questionnaires/",
        "name": "audio_2",
        "avsc": "questionnaire"
      },
      "startText": {
        "en": "",
        "it": "",
        "nl": "",
        "da": "",
        "de": "",
        "es": ""
      },
      "endText": {
        "en": "",
        "it": "",
        "nl": "",
        "da": "",
        "de": "",
        "es": ""
      },
      "warn": {
        "en": "Find a quiet space.",
        "it": "Trova uno spazio tranquillo.",
        "nl": "Zoek een stille ruimte.",
        "da": "Find et roligt sted.",
        "de": "Suchen Sie sich einen ruhigen Platz.",
        "es": "Encuentra un espacio tranquilo."
      },
      "estimatedCompletionTime": 3,
      "protocol": {
        "repeatProtocol": {
          "unit": "day",
          "amount": 42
        },
        "repeatQuestionnaire": {
          "unit": "min",
          "unitsFromZero": [20850]
        },
        "reminders": {
          "unit": "day",
          "amount": 0,
          "repeat": 0
        },
        "completionWindow": {
          "unit": "day",
          "amount": 3
        }
      }
    },
    {
      "name": "AUDIO_3",
      "showIntroduction": false,
      "questionnaire": {
        "repository": "https://raw.githubusercontent.com/RADAR-base/RADAR-REDCap-aRMT-Definitions/master/questionnaires/",
        "name": "audio_3",
        "avsc": "questionnaire"
      },
      "startText": {
        "en": "",
        "it": "",
        "nl": "",
        "da": "",
        "de": "",
        "es": ""
      },
      "endText": {
        "en": "",
        "it": "",
        "nl": "",
        "da": "",
        "de": "",
        "es": ""
      },
      "warn": {
        "en": "Find a quiet space.",
        "it": "Trova uno spazio tranquillo.",
        "nl": "Zoek een stille ruimte.",
        "da": "Find et roligt sted.",
        "de": "Suchen Sie sich einen ruhigen Platz.",
        "es": "Encuentra un espacio tranquilo."
      },
      "estimatedCompletionTime": 3,
      "protocol": {
        "repeatProtocol": {
          "unit": "day",
          "amount": 42
        },
        "repeatQuestionnaire": {
          "unit": "min",
          "unitsFromZero": [41010]
        },
        "reminders": {
          "unit": "day",
          "amount": 0,
          "repeat": 0
        },
        "completionWindow": {
          "unit": "day",
          "amount": 3
        }
      }
    }
  ]
}
